/**
 * Database types - Auto-generated from Supabase
 * Run `npx supabase gen types typescript` to regenerate
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      stores: {
        Row: {
          id: string;
          peeap_merchant_id: string;
          peeap_user_id: string;
          slug: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          favicon_url: string | null;
          email: string | null;
          phone: string | null;
          address: Json | null;
          currency: string;
          timezone: string;
          settings: Json;
          theme_id: string | null;
          custom_theme: Json;
          custom_css: string | null;
          status: string;
          is_featured: boolean;
          show_in_marketplace: boolean;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          peeap_merchant_id: string;
          peeap_user_id: string;
          slug: string;
          name: string;
          description?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: Json | null;
          currency?: string;
          timezone?: string;
          settings?: Json;
          theme_id?: string | null;
          custom_theme?: Json;
          custom_css?: string | null;
          status?: string;
          is_featured?: boolean;
          show_in_marketplace?: boolean;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          peeap_merchant_id?: string;
          peeap_user_id?: string;
          slug?: string;
          name?: string;
          description?: string | null;
          logo_url?: string | null;
          favicon_url?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: Json | null;
          currency?: string;
          timezone?: string;
          settings?: Json;
          theme_id?: string | null;
          custom_theme?: Json;
          custom_css?: string | null;
          status?: string;
          is_featured?: boolean;
          show_in_marketplace?: boolean;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      products: {
        Row: {
          id: string;
          store_id: string;
          name: string;
          slug: string;
          description: string | null;
          short_description: string | null;
          price: number;
          compare_at_price: number | null;
          cost_price: number | null;
          currency: string;
          sku: string | null;
          barcode: string | null;
          inventory_quantity: number;
          track_inventory: boolean;
          allow_backorder: boolean;
          weight: number | null;
          weight_unit: string;
          images: Json;
          category_id: string | null;
          tags: string[];
          status: string;
          is_featured: boolean;
          meta_title: string | null;
          meta_description: string | null;
          has_variants: boolean;
          options: Json;
          view_count: number;
          sales_count: number;
          created_at: string;
          updated_at: string;
          published_at: string | null;
        };
        Insert: {
          id?: string;
          store_id: string;
          name: string;
          slug: string;
          description?: string | null;
          short_description?: string | null;
          price: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          currency?: string;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number;
          track_inventory?: boolean;
          allow_backorder?: boolean;
          weight?: number | null;
          weight_unit?: string;
          images?: Json;
          category_id?: string | null;
          tags?: string[];
          status?: string;
          is_featured?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          has_variants?: boolean;
          options?: Json;
          view_count?: number;
          sales_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
        Update: {
          id?: string;
          store_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          short_description?: string | null;
          price?: number;
          compare_at_price?: number | null;
          cost_price?: number | null;
          currency?: string;
          sku?: string | null;
          barcode?: string | null;
          inventory_quantity?: number;
          track_inventory?: boolean;
          allow_backorder?: boolean;
          weight?: number | null;
          weight_unit?: string;
          images?: Json;
          category_id?: string | null;
          tags?: string[];
          status?: string;
          is_featured?: boolean;
          meta_title?: string | null;
          meta_description?: string | null;
          has_variants?: boolean;
          options?: Json;
          view_count?: number;
          sales_count?: number;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
        };
      };
      orders: {
        Row: {
          id: string;
          store_id: string;
          order_number: string;
          customer_email: string;
          customer_name: string | null;
          customer_phone: string | null;
          peeap_user_id: string | null;
          shipping_address: Json;
          billing_address: Json | null;
          subtotal: number;
          shipping_cost: number;
          tax_amount: number;
          discount_amount: number;
          total: number;
          currency: string;
          peeap_checkout_session_id: string | null;
          peeap_transaction_id: string | null;
          payment_status: string;
          fulfillment_status: string;
          order_status: string;
          payout_status: string;
          payout_amount: number | null;
          platform_fee: number | null;
          payout_release_at: string | null;
          shipping_method: string | null;
          tracking_number: string | null;
          tracking_url: string | null;
          shipped_at: string | null;
          delivered_at: string | null;
          customer_notes: string | null;
          internal_notes: string | null;
          discount_code: string | null;
          discount_id: string | null;
          source: string;
          source_url: string | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          store_id: string;
          order_number?: string;
          customer_email: string;
          customer_name?: string | null;
          customer_phone?: string | null;
          peeap_user_id?: string | null;
          shipping_address: Json;
          billing_address?: Json | null;
          subtotal: number;
          shipping_cost?: number;
          tax_amount?: number;
          discount_amount?: number;
          total: number;
          currency?: string;
          peeap_checkout_session_id?: string | null;
          peeap_transaction_id?: string | null;
          payment_status?: string;
          fulfillment_status?: string;
          order_status?: string;
          payout_status?: string;
          payout_amount?: number | null;
          platform_fee?: number | null;
          payout_release_at?: string | null;
          shipping_method?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          customer_notes?: string | null;
          internal_notes?: string | null;
          discount_code?: string | null;
          discount_id?: string | null;
          source?: string;
          source_url?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          store_id?: string;
          order_number?: string;
          customer_email?: string;
          customer_name?: string | null;
          customer_phone?: string | null;
          peeap_user_id?: string | null;
          shipping_address?: Json;
          billing_address?: Json | null;
          subtotal?: number;
          shipping_cost?: number;
          tax_amount?: number;
          discount_amount?: number;
          total?: number;
          currency?: string;
          peeap_checkout_session_id?: string | null;
          peeap_transaction_id?: string | null;
          payment_status?: string;
          fulfillment_status?: string;
          order_status?: string;
          payout_status?: string;
          payout_amount?: number | null;
          platform_fee?: number | null;
          payout_release_at?: string | null;
          shipping_method?: string | null;
          tracking_number?: string | null;
          tracking_url?: string | null;
          shipped_at?: string | null;
          delivered_at?: string | null;
          customer_notes?: string | null;
          internal_notes?: string | null;
          discount_code?: string | null;
          discount_id?: string | null;
          source?: string;
          source_url?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          parent_id: string | null;
          level: number;
          path: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          level?: number;
          path?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          level?: number;
          path?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}

// Convenience types
export type Store = Database['public']['Tables']['stores']['Row'];
export type Product = Database['public']['Tables']['products']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type Category = Database['public']['Tables']['categories']['Row'];
